#!/usr/bin/env bash

ip_eth = $(ip -4 addr show dev enp5s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
ip_wlan = $(ip -4 addr show dev wlo1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')


if [ -z "$ip_eth" ] && [ -z "$ip_wlan" ]; then
    echo "Ip is empty"
elif [ -z "$ip_eth" ] || [ -z "$ip_wlan" ]; then
    echo "$ip_eth$ip_wlan"
fi
